### PR TITLE
Add Support FreeRTOS

### PR DESCRIPTION
**Pull request by alexmrtn**
This PR is to add support for FreeRTOS.

We filled the blanks in the c-utility so that thread are mapped on Freertos tasks, and conditions to the native freertos conditions. 

We had to modify a bit the memory function used when using custom heap in order to secure the malloc / realloc calls when on freertos.

Please let us know if this PR make sens to you and if it needs any modifications.

Best,
Alexis Martin.

### CODE REVIEW

**Comment by yzhong94** [comment]
@alexmrtn we are reviewing this internally now.  Thank you!

**Comment by ewertons** [comment]
@alexmrtn ,
thanks for your PR.
We are working on our supportability infrastructure and we will need to assess how to onboard these changes (which will require adding tests, add proper devices to our build lab, etc).
We will keep this PR open until we close on those definitions.

**Comment by ewertons** [comment]
@alexmrtn ,
just to gather some more info, would you mind sharing:
1. What is the device/platform you used for testing your changes?
2. Which TLS api you used?
3. What IP stack you used?
4. Did you use one of our PAL layers?

**Comment by alexmrtn** [comment]
@ewertons 

Thanks for the details about the following of this PR. I entirely understand that it will add some validation work if this come to the official support.

1. We have developed the changes using the Posix/Linux Simulator for FreeRTOS, and then manually validated the functions on a stm32F429 Nucleo Board.
2. We used the mbedTLS adapter (the one we make through #270)
3. We used Lwip
4. Yes we have used the following files:
    - lock.c (No modification)
    - threadapi.c (with modifications)
    - tickcounter.c (with minor modifications)
    - platform_freertos.c (with minor modifications)
    - condition_freertos.c (new file created)
    - socketio_berkeley.c (minor modifications to be able to bind to Berkeley sockets API adapter of lwip )

Let me know if I can help / provide you more details.

**Pull request closed without merging**
