### PR TITLE
Do not pass MSG_NOSIGNAL as flag to `recv`

### PR DESCRIPTION
**Pull request by AndWass**
Related issue: https://github.com/Azure/azure-c-shared-utility/issues/605

### CODE REVIEW

**Comment by danewalton** [comment]
Hi @AndWass 
The flag for `MSG_NOSIGNAL` was explicitly added in this PR: https://github.com/Azure/azure-c-shared-utility/pull/479

It should only suppress the SIGPIPE error, reducing the number of errors this would actually generate. This change, as I understand, would create more error scenarios.

**Comment by danewalton** [comment]
https://www.man7.org/linux/man-pages/man2/recv.2.html

Doesn't seem to be a flag for `recv()`

**Comment by AndWass** [comment]
That was my reading/take on it as well.

**Review by danewalton — APPROVED** [review]

**Pull request merged**
