### PR TITLE
decorate unused parameter

### PR DESCRIPTION
**Pull request by fanzhe98**
decorate unused parameter in tlsio_wolfssl.c #480

### CODE REVIEW

**Review by momuno — APPROVED** [review]

**Comment by momuno** [comment]
@fanzhe98 this is causing the build to fail.  Why is it passing in the build Azure Sphere is using?

**Comment by fanzhe98** [comment]
@momuno yeah, possibly the depedencies in azure sphere that made this work though in 
xlogging.h there is ``` #define UNUSED(x) (void)(x)```

changing it to```void(name)``` should be the same

eddited.

**Comment by momuno** [comment]
> @momuno yeah, possibly the depedencies in azure sphere that made this work though in
> xlogging.h there is ` #define UNUSED(x) (void)(x)`
> 
> changing it to`void(name)` should be the same
> 
> eddited.

I see tlsio_wolfssl.c has
```
#include "azure_c_shared_utility/xlogging.h"
```
peculiar why it didn't compile.  Thanks for making the update.

**Pull request merged**
