### PR TITLE
Fix: Failure to reconnect after network issues.

### PR DESCRIPTION
**Pull request by dbuijsma**
https://github.com/Azure/azure-c-shared-utility/issues/105

### CODE REVIEW

**Comment by ewertons** [comment]
Hello @dbuijsma, I will be verifying your PR today. 
Thanks for contributing to the Azure IoT SDKs.

**Comment by dbuijsma** [comment]
Let me know if you need more info. It took us some time to figure out what was going on and we have trace information which shows how we got in the error states. They are not too easy to reproduce either.

**Comment by ewertons** [comment]
Hi @dbijsma,

upon reviewing the PR we see there is a lot of code change that we would need to validate, possibly impacting a lot of other components that depend on this socket implementation. 
Let me pause on taking the code changes in for now and investigate the initial issue first.
Most likely the fix will be a subset of the changes you are proposing.
We will come back to you briefly with an update.

Thanks a lot for contributing to the Azure IoT C SDK,

**Comment by jebrando** [comment]
This has been merged into the repo.  Thanks you

**Pull request closed without merging**
