### PR TITLE
[DO NOT MERGE] Async DNS resolver implementation

### PR DESCRIPTION
**Pull request by massand**
We are planning to add a asynchronous DNS resolution helper for the socket_io layers that can support the c-ares library (which is quite portable across many platforms). 

This PR supports Windows and Linux platform only, so that we can vet the PAL changes for socket and dns_async addition. The plan is to leverage vcpkg / apt-get packages to obtain c-ares dependencies or assuming c-ares is part of your toolchain's sysroot/lib and /include (i.e. we do not plan to submodule c-ares). 

**How to build & test using iothub_ll_telemetry_sample on Windows with azure-iot-sdk-c** 
(**note**: an IoTHub connection string is required in azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c): 

- Install c-ares vcpkg
```
git clone https://github.com/Microsoft/vcpkg.git vcpkg_new
pushd vcpkg_new
.\bootstrap-vcpkg.bat
vcpkg integrate install
vcpkg install c-ares
```

-  Build SDK with async dns_resolver
```
git clone https://github.com/Azure/azure-iot-sdk-c.git 
cd azure-iot-sdk-c
git checkout 1078a7bf699707ddddb8b2e08b57e1f8454a3cde
git submodule update --init --recursive
pushd c-utility
git fetch
git checkout dns_resolver
popd
pushd umqtt\deps\c-utility
git fetch
git checkout dns_resolver
popd
mkdir cmake
cmake ..
cmake --build . -- /m /p:Configuration=Debug
iothub_client\samples\iothub_ll_telemetry_sample\Debug\iothub_ll_telemetry_sample.exe
```

In order to switch to the default synchronous DNS resolution, simply change the c-utility\CMakeLists.txt to dns_resolver_sync.c

**How to build & test using iothub_ll_telemetry_sample on Linux with azure-iot-sdk-c** 
(**note**: an IoTHub connection string is required in azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c) -
 
```
sudo apt install libc-ares-dev
git clone https://github.com/Azure/azure-iot-sdk-c.git 
cd azure-iot-sdk-c
git checkout 1078a7bf699707ddddb8b2e08b57e1f8454a3cde
git submodule update --init --recursive
pushd c-utility
git fetch
git checkout dns_resolver_berkley
popd
pushd umqtt/deps/c-utility
git fetch
git checkout dns_resolver_berkley
popd
mkdir cmake
cd cmake
cmake ..
cmake --build .
pushd iothub_client/samples/iothub_ll_telemetry_sample
./iothub_ll_telemetry_sample
```

### CODE REVIEW

**Comment by angelobt** [comment]
Hi,
I have some problem compiling the shared utility package

/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -DARCHITECTURE_ARM=1 -Daziotsharedutil_dll_EXPORTS -I/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/inc -I/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/pal/linux -D_POSIX_C_SOURCE=200112L  -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9  --sysroot=/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0=/usr/src/debug/azure-c-shared-utility/1.1.4-r0 -fdebug-prefix-map=/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/recipe-sysroot= -fdebug-prefix-map=/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/recipe-sysroot-native=   -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9  --sysroot=/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/recipe-sysroot -Werror -Werror -Wall -Wextra -Wformat=2 -Wformat-security -DUSE_OPENSSL -Wno-unused-variable -Wno-missing-braces -Wno-missing-field-initializers -Wno-format-nonliteral -fPIC -MD -MT CMakeFiles/aziotsharedutil_dll.dir/src/uws_client.c.o -MF CMakeFiles/aziotsharedutil_dll.dir/src/uws_client.c.o.d -o CMakeFiles/aziotsharedutil_dll.dir/src/uws_client.c.o   -c /home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/uws_client.c
ninja: build stopped: subcommand failed

Do you have you any suggestion ?
I'm using Yocto (sumo) and I'm cross-compiling for arm

Thanks

**Comment by angelobt** [comment]
Ater removing from recipe -j 16 I get these errors

/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:102:5: error: unkn
own type name 'ADDRINFO'; did you mean 'EADDRINUSE'?
     ADDRINFO *ai;
     ^~~~~~~~
     EADDRINUSE
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:103:5: error: unkn
own type name 'ADDRINFO'; did you mean 'EADDRINUSE'?
     ADDRINFO *firstai = NULL;
     ^~~~~~~~
     EADDRINUSE
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:104:5: error: unkn
own type name 'ADDRINFO'; did you mean 'EADDRINUSE'?
     ADDRINFO *prevai = NULL;
     ^~~~~~~~
     EADDRINUSE
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:111:38: error: 'AD
DRINFO' undeclared (first use in this function); did you mean 'EADDRINUSE'?
     dns->addrInfo = calloc(1, sizeof(ADDRINFO));
                                      ^~~~~~~~
                                      EADDRINUSE
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:111:38: note: each undeclared identifier is reported only once for each function it appears in
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:122:11: error: request for member 'ai_canonname' in something not a structure or union
         ai->ai_canonname = _strdup(he->h_name);
           ^~
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:122:28: error: implicit declaration of function '_strdup'; did you mean 'strcmp'? [-Werror=implicit-function-declaration]
         ai->ai_canonname = _strdup(he->h_name);
                            ^~~~~~~
                            strcmp
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:123:16: error: request for member 'ai_canonname' in something not a structure or union
         if (!ai->ai_canonname) {
                ^~
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:127:11: error: request for member 'ai_addr' in something not a structure or union
         ai->ai_addr = calloc(1, ss_size);
           ^~
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:128:16: error: request for member 'ai_addr' in something not a structure or union
         if (!ai->ai_addr) {
                ^~
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:129:20: error: request for member 'ai_canonname' in something not a structure or union
             free(ai->ai_canonname);
                    ^~
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:140:19: error: request for member 'ai_next' in something not a structure or union
             prevai->ai_next = ai;
                   ^~
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:142:11: error: request for member 'ai_family' in something not a structure or union
         ai->ai_family = he->h_addrtype;
           ^~
/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-c-shared-utility/1.1.4-r0/git/src/dns_resolver_ares.c:146:11: error: request for member 'ai_socktype' in something not a structure or union
         ai->ai_socktype = SOCK_STREAM;
           ^~

**Comment by angelobt** [comment]
Hi,
it seems that it compiles only for windows.
I need the linux version

**Comment by massand** [comment]
Yes - this change is being initially verified on Windows. There is some progress made on the berkeley Linux version [at this branch](https://github.com/Azure/azure-c-shared-utility/commits/dns_resolver_berkley). However, I am running into some issue in the post-resolution stage within query_completed_cb, which I did not hit on Windows. I will post back when I resolve the issue. I had to run the 'sudo apt install libc-ares-dev' command on Linux to test this.

**Comment by massand** [comment]
@angelobt - i have a fix for the berkeley socket issue now, which I tested using the sample at iothub_client/samples/iothub_ll_telemetry_sample. I have updated the validation steps in the PR description comment. Please follow those steps and let me know if you run into issues building. 

As mentioned earlier, I need to run a lot more validation across all our supported compiler/platforms for the socketio and dns_resolver changes. In the meantime, please provide your feedback on the DNS resolution experience on your Linux environment,

**Comment by angelobt** [comment]
Hi,
sorry for this question, but I have to use Yocto environment to test your new implementation:

I have set all repos to the right commit (I hope), but when compiling the c sdk I get the following error:

make -E __create_def /home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0/build/ioth
ub_client/CMakeFiles/iothub_client_dll.dir/exports.def /home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/a
zure-iot-sdk-c/1.2.4-r0/build/iothub_client/CMakeFiles/iothub_client_dll.dir/exports.def.objs && cd /home/sources/C100X/shark/poky-
tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0/build && /home/sources/C100X/shark/poky-tmp/work/cortexa9hf-ne
on-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -fPI
C -fPIC  -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9  --sysroot=/home/sources/C100X/shark/poky-tmp/work/cortex
a9hf-neon-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-ma
p=/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0=/usr/src/debug/azure-iot-sdk-c/1.2.4-r0 -fdebug-prefix-map=/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0/recipe-sysroot= -fdebug-prefix-map=/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0/recipe-sysroot-native=   -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9  --sysroot=/home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0/recipe-sysroot -w -Werror  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -shared -Wl,-soname,libiothub_client.so.1 -o iothub_client/libiothub_client.so.1.2.14 iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_client.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_client_core.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_client_core_ll.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_client_diagnostic.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_client_ll.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_device_client.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_device_client_ll.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_message.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_module_client.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_module_client_ll.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransport.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/version.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_client_ll_uploadtoblob.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/blob.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_client_authorization.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_client_retry_control.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothub_transport_ll_private.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransporthttp.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransport_amqp_common.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransport_amqp_device.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransport_amqp_cbs_auth.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransport_amqp_connection.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransport_amqp_telemetry_messenger.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransport_amqp_twin_messenger.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransport_amqp_messenger.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransportamqp_methods.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/message_queue.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/uamqp_messaging.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransportamqp.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransportamqp_websockets.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransport_mqtt_common.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransportmqtt.c.o iothub_client/CMakeFiles/iothub_client_dll.dir/src/iothubtransportmqtt_websockets.c.o  iothub_client/libiothub_client_http_transport.a iothub_client/libiothub_client_amqp_transport.a iothub_client/libiothub_client_amqp_ws_transport.a iothub_client/libiothub_client_mqtt_transport.a iothub_client/libiothub_client_mqtt_ws_transport.a libparson.a -Wl,--exclude-libs,libparson.a /home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0/recipe-sysroot/usr/lib/libumqtt.so.1.1.4 /home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0/recipe-sysroot/usr/lib/libaziotsharedutil.a -lcurl -lssl -lcrypto -lpthread -lm -lrt -luuid -lcares && :
CMake Error: cmake version 3.10.3
Usage: /home/sources/C100X/shark/poky-tmp/work/cortexa9hf-neon-poky-linux-gnueabi/azure-iot-sdk-c/1.2.4-r0/recipe-sysroot-native/usr/bin/cmake -E <command> [arguments...]

Seems that after compiling the libraries, a cmake -E __create_def command is executed, but, I think it is related to windows.
Do you know how to disable it via Cmake ?
Thanks

**Comment by angelobt** [comment]
Hi,

after updating Cmake, the compilation succeeded.
Now  I have a SIGSEV runtime.

seems that the function where the library dies is ResetConnectionIfNecessary when calling
xio_destroy.

I get "free(): invalid pointer" message

**Comment by angelobt** [comment]
Hi Rajeev,
in order to test c-ares async dns resolution, I had to comment out some "free" inside the code **to avoid sigsev**.
Seems that the resolution works well and the library does not block anymore waiting for dns.

**These are the commit I have used:**
git://github.com/Azure/azure-iot-sdk-c.git;rev=1078a7bf699707ddddb8b2e08b57e1f8454a3cde

git://github.com/Azure/azure-c-shared-utility.git;branch=dns_resolver_berkley;rev=bf0a197b3bcf1d92e1d22661480032ca7889e5a6;destsuffix=git/c-utility

git://github.com/Azure/azure-umqtt-c.git;rev=6cd0cdeba607ed8de2e129e3451ef956f8ddf383;destsuffix=git/umqtt

git://github.com/Azure/azure-uamqp-c.git;rev=13f009ddd50a2837f651b0237de17db5f24c3af9;destsuffix=git/uamqp

git://github.com/kgabis/parson.git;rev=302fba9cbb31ffc523bf10a1ce705040194c289d;destsuffix=git/deps/parson

git://github.com/Azure/azure-uhttp-c.git;rev=43dce924b32818f8ab851f972cffebc204edc5c4;destsuffix=git/deps/uhttp \

**I had to comment:**
xio_destroy called by ResetConnectionIfNecessary and mqtt_disconnect_cb

handleData->IoTHubTransport_Destroy called by IoTHubClientCore_LL_Destroy

**Comment by massand** [comment]
@angelobt - we are still working on improving this code and not planning to release this month, due to significant refactors in submodules (which need to be merged in here). Moreover, we need to also align with the TLS stack of some other platforms that also have async DNS. 

That said, you still have code to help accelerate your development in the dns_resolver_berkley branch. I have updated the PR instructions on how to set it up for Linux (when building from scratch) - 

(note: an IoTHub connection string is required in azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c) -

sudo apt install libc-ares-dev
git clone https://github.com/Azure/azure-iot-sdk-c.git 
cd azure-iot-sdk-c
git checkout 1078a7bf699707ddddb8b2e08b57e1f8454a3cde
git submodule update --init --recursive
pushd c-utility
git fetch
git checkout dns_resolver_berkley
popd
pushd umqtt/deps/c-utility
git fetch
git checkout dns_resolver_berkley
popd
mkdir cmake
cd cmake
cmake ..
cmake --build .
pushd iothub_client/samples/iothub_ll_telemetry_sample
./iothub_ll_telemetry_sample

**Comment by angelobt** [comment]
@massand 
I have compiled the SDK but the first time I call
IoTHubClient_LL_DoWork function I get SIGSEGV (free invalid pointer)

azure-iot-sdk-c rev=1078a7bf699707ddddb8b2e08b57e1f8454a3cde
azure-umqtt-c rev=4fca26efad8f9ea9b4beb143099758314bd32e41
azure-uamqp-c rev=bae40b9d9a3939f666dc9ea137ba64e2b9fc0fb7
azure-c-shared-utility rev=8cccfe3f303b92740d86012077ea60abf254f0bd (dns_resolver_berkley)

Regards,
Angelo

**Comment by angelobt** [comment]
Hi,
in dns_resolver_create() function, DNSRESOLVER_INSTANCE struct is allocated with malloc and addrInfo field is not initialized. So if dns_resolver_destroy() is called before that field was initialized,
we get  free(): invalid pointer error.
Using calloc instead of malloc or initializing addrInfo field to NULL fixes the issue.

Please could you consider to use every time calloc instead of malloc ?

Best regards

**Comment by massand** [comment]
I will reopen a new PR for this one when ready. Working on UTs and samples.

**Pull request closed without merging**
