### PR TITLE
fix setting ssl property for iOS 10.x on iPhone 5

### LINKED ISSUE #229: Crash on iphone5c iOS 10.3.3
Application crashes on that line on iPhone 5c iOS 10.3.3

https://github.com/Azure/azure-c-shared-utility/blob/bcf6393b1ce3cecf0fcdf8988621fd6e4d414df3/pal/ios-osx/tlsio_appleios.c#L524

### PR DESCRIPTION
**Pull request by chlandsi**
Fix arguments according to https://developer.apple.com/documentation/cfnetwork/kcfstreampropertysslsettings?language=objc.

Original code resulted in an EXC_ARITHMETIC (code=EXC_I386_DIV, subcode=0x0) error from the CFReadStreamSetProperty call on iOS 10.x simulator.

This might fix #229.

### CODE REVIEW

**Comment by dnsmirnoff** [comment]
This PR fixes #229. I've tested it on iPhone 5c with iOS 10.3.3

**Comment by danewalton** [comment]
Hi @chlandsi this section of the code has been updated integrating a lot of your suggestions. Please see the code below and let us know if that fixes the issue. For now I'm going to close this since many of the changes are already merged.
https://github.com/Azure/azure-c-shared-utility/blob/2d74785c2b475ca94321114a23f8007094bdac11/pal/ios-osx/tlsio_appleios.c#L529-L538

**Pull request closed without merging**
